#!/usr/bin/env bash

# NOTE:
#   A much better solution to the same program is the `sponge` utility from the
#   `moreutils` package.
#   instead of
#   $ filterfile <filename> <command>
#   you do
#   $ <command> <filename> | ... | sponge <filename>

# TODO In a perfect world, this would essentially be a macro.
# I want to have this take any furthur string on the commmand line
# and make the command line below to execute.
# cat $1 | ${@:2} > $tmpfile
#
# Currently, I can't get this to work without bash expanding the variables
# in inconveniant ways.
# I will try to keep an eye out for anything that makes the possible.
set -e
tmpfile=$(mktemp -u XXXXXX)
"${@:2}" < "$1" > "$tmpfile"
chmod $(stat -c "%a" "$1") "$tmpfile"
mv "$tmpfile" "$1"
