#!/bin/bash

repeated_command=$(basename ${0%i})

while read -ep "> " line
do
    # Two cases to account for:
    #     If there's quotes in the string, need xargs for parsing tokens
    #     If call 'commit' within xargs, the vim instance ran causes some
    #     errors.
    if [[ "$line" == *'"'* ]]
    then
        echo $line | xargs $repeated_command
    else
        $repeated_command $line
    fi
done
