#!/bin/bash

# Problems with this script:
#       Have no history to work with.

while read -ep "> " line
do
    if [[ "$line" == "quit" ]]
    then
        break
    fi
    # Two cases to account for:
    #     If there's quotes in the string, need xargs for parsing tokens
    #     If call 'commit' within xargs, the vim instance ran causes some
    #     errors.
    if [[ "$line" == *'"'* ]]
    then
        echo $line | xargs git
    else
        git $line
    fi
done
