#!/bin/bash

# Have had some trouble with solaris not having the maxdepth argument,
# currently assuming the trouble is only in solaris, but could be in other
# linux distros as well.
if [[ $OSTYPE =~ 'solaris' ]]; then
    gfind ${PATH//:\// /} -maxdepth 1 -name "$@"
else
    find ${PATH//:\// /} -maxdepth 1 -name "$@"
fi
