#!/bin/sh
#
# ~/.xinitrc
#
# remove uneeded path from xset, add extra ones for terminus font.
xset -fp /usr/share/fonts/OTF/
xset +fp /usr/share/fonts/local/
xset +fp /usr/share/fonts/artwiz-fonts/
xset fp rehash

# Executed by startx (run your window manager from here)

if [ -d /etc/X11/xinit/xinitrc.d ]; then
  for f in /etc/X11/xinit/xinitrc.d/*; do
    [ -x "$f" ] && . "$f"
  done
  unset f
fi


# Default is awesome - I get much more work done there
# to get pekwm etc, have to run with xinitrc, not startx

# Some window managers have a startup script some don't
# so I've loaded my compensation for broken key here for those.

# Really need to figure out how to neaten this up - want some to start on
# boot, and some to start/finish when entering/leaving X
#
# systemd has stopped working like I thought it should - comment out for now
# /usr/lib/systemctl --user is-active default.target || /usr/lib/systemd/systemd --user &

# This would be handled by systemd, if the thing worked as I think it should
sxhkd -c ~/.config/sxhkd/sxhkdrc -r ~/.cache/sxhkd/output &

# Loads the non-colour  xresources, the colours are chosen based on wm
xrdb -load ~/xresources/base_resources


pek_start () {
    xrdb -merge ~/xresources/$1
    feh --bg-fill ~/.config/wallpapers/$2 &
    exec pekwm --config ~/.config/pekwm/$3
}


subtle_start () {
    unclutter -idle 4 -jitter 2 -root
    xrdb -merge ~/xresources/$1
    feh --bg-fill ~/.config/wallpapers/$2
    xmodmap ~/xmodmaps/xmodmap_super
    exec subtle >> ~/.cache/subtle/stdout 2>> ~/.cache/subtle/stderr
}


awesome_start () {
    xrdb -merge ~/xresources/$1
    xmodmap ~/xmodmaps/xmodmap_super
    ln -sf ~/.config/awesome/the_rcs/${2}.lua ~/.config/awesome/rc.lua
    exec awesome >> ~/.cache/awesome/stdout 2>> ~/.cache/awesome/stderr
}

case $1 in
    "pek_woman")    pek_start standard_but_calmer multiimage_woman.jpg config
                    ;;

    "pek_build")    pek_start standard_but_calmer skippin___skool_by_ether.jpg config
                    ;;

     "pek_pier")    pek_start awesome_personal_resources pier_house.jpg windmill
                    ;;

    "pek_windmill") pek_start vinyl windmill_sillhouette.jpg windmill
                    ;;

    "subtle_new")   subtle_start awesome_personal_resources earthrise_1.jpg
                    ;;

    "subtle_orig")  subtle_start subtle_initial_resources block_colours_woman_sunglasses.jpg
                    ;;

    "ratpoison")    xrdb -merge ~/xresources/awesome_personal_resources
                    feh --bg-fill ~/.config/wallpapers/earthrise_1.jpg
                    xmodmap ~/xmodmaps/xmodmap_control
                    exec /usr/bin/ratpoison -f ~/.config/ratpoison/ratpoisonrc
                    ;;

    "shifty")       awesome_start awesome_personal_resources shifty
                    ;;

    "holo")         awesome_start holo holo
                    ;;

    "dust")         awesome_start vinyl dust
                    ;;

    "multicolor")    awesome_start dremora multicolor
                    ;;

    "steamburn")    awesome_start steamburn steamburn
                    ;;

    "muted")        awesome_start awesome_muted_resources muted
                    ;;

    *)              awesome_start awesome_personal_resources main
                    ;;
esac
