
export HISTCONTROL=ignoreboth
export LESSHISTFILE="/dev/null"

# Default editor vim
export EDITOR=vim
export PAGER=less


# Add $HOME/bin to $PATH
typeset -U path
if [ -d "$HOME/bin" ]; then
    path=(~/bin $path)
fi
if [ -d "$HOME/.gem/ruby/2.0.0/bin/" ]; then
    path=(~/.gem/ruby/2.0.0/bin $path)
fi
