# This adds colors to ALL less instances, might be annoying in some cases.
# N.b. using escape literally rather than `printf` because `gdbserver` hangs
# whenever used if `zshenv` forks.  Just avoid that strange bug.
# https://sourceware.org/bugzilla/show_bug.cgi?id=26116
export LESS_TERMCAP_mb="[1;31m"
export LESS_TERMCAP_md="[1;31m"
export LESS_TERMCAP_me="[0m"
export LESS_TERMCAP_se="[0m"
export LESS_TERMCAP_so="[1;44;33m"
export LESS_TERMCAP_ue="[0m"
export LESS_TERMCAP_us="[1;32m"


export IPYTHONDIR="~/.config/ipython"
export HISTCONTROL=ignoreboth
export LESSHISTFILE="/dev/null"
export LESS="-SR -j 5"

if [[ $TERM == 'dumb' ]]; then
  export PAGER=
  # Usually I would want $MANPAGER set to col -b, if I'm running in vsh, then
  # I've already set $MANPAGER to 'col -b | cat', which obviously does the
  # same but buffers the output so it doesn't make nvim slow.
  if [[ -z "$MANPAGER" ]]; then
    export MANPAGER='col -b'
  fi
else
  if [ -d "$HOME/bin/neovim/bin/" ]; then
    export EDITOR=${HOME}/bin/neovim/bin/nvim
  else
    export EDITOR=vim
  fi
  export PAGER=less
  # Allow git filter-branch without the warning.
  export FILTER_BRANCH_SQUELCH_WARNING=1
fi

export MANSECT=1:8:5:7:2:0:3:4:6

# Declare $path to only have unique elements.
typeset -U path
typeset -U PATH
# Declare infopath array variable as tied to the INFOPATH environment variable.
# This means I can just add to an array rather than having to manage the case
# when there is no existing INFOPATH and I end up with an erroneous extra ':' at
# the start of the variable.  N.b. while the `info` command line utility already
# searches directories related to PATH for anything that could be an INFO
# directory, Emacs initilises its own internal info directory list ignoring
# PATH.  Using INFOPATH to make the two look in the same places.
typeset -xT INFOPATH infopath ':'
typeset -U infopath
infopath=(/usr/share/info)
add_to_path () {
  if [ -d "$1" ]; then
    path=("$1" $path)
    if [ -n "$2" ]; then
      infopath=("$2" $infopath)
    fi
  fi
}
add_to_path "$HOME/bin"

add_to_path "$HOME/repos/binutils/install/bin" "$HOME/repos/binutils/install/share/info"
add_to_path "$HOME/bin/emacs/bin" "$HOME/bin/emacs/share/info"
add_to_path "$HOME/.local/bin"
add_to_path "$HOME/.gem/ruby/2.1.0/bin"
# Add zsh completion directory to fpath
add_to_path "$HOME/.config/zsh/completion"
add_to_path "$HOME/.cargo/bin"
add_to_path "$HOME/bin/lua-lsp/bin"
add_to_path "$HOME/bin/rr/bin"
