#!/usr/bin/gawk -f

BEGIN {
	FS = "	";
}

# Ignore lines beginning with an exclamation mark.
!/^!/ {
	sub(/;/, "	", $3);
	printf("%s	%s:%s", $1, $2, $3);
	for (i = 4; i < NF + 1; i++)
		print FS, $i;
}